### ISSUE TITLE
Milestone1  to do list

### ISSUE THREAD

**Issue by lennonay** [UBC-MDS/covid_viz#2]
To Do List:
- Code of Conduct - Jenit Jain
- Teamwork contract - Jenit Jain
- Contribution guidelines - Lennon Au-Yeung
- Description of your app & sketch - Lennon Au-Yeung and Jenit Jain
- Start developing your app - Ashwin Babu
- Research questions you are exploring - Ashwin Babu
- Motivation and purpose - Bruce Wu
- Description of the data - Bruce Wu

**Comment by ashwin2507** [comment]
Completed.
